### ISSUE TITLE
Intl locales can't be loaded

### ISSUE THREAD

**Issue by okovpashko** [jquintozamora/polyfill-io-feature-detection#2]
Hi. I'm trying to use this package for loading Intl polyfill. For correct work, it needs also `Intl.~locale.[locale]` to be loaded. But if I try to add any locale to features I get the next message: 
> Feature Intl.~locale.en-US can not be detected because it has not JavaScript API.

What if instead of skipping features with `~` this tool will include them in the query string for polyfill.io if the root feature (like `Intl` for `Intl.~locale.en-US`) is not supported by the browser?

**Comment by jquintozamora** [comment]
Hi @okovpashko ,

Thank you for your feedback. Indeed, it was a bug, I have solve it in the release 1.1.14.
Please update your npm package and let me know if that worked for you!

Regards!

**Comment by okovpashko** [comment]
Thanks a lot!
