### ISSUE TITLE
Add support for IE7 & IE8

### ISSUE THREAD

**Issue by ridem** [jquintozamora/polyfill-io-feature-detection#3]
For the sake of supporting polyfill.io fully, you may want to support IE7 & IE8 in the code base. Two things are needed :
- Not using unsupported features in the codebase itself
- More robust `loadScript`

### Features
Features impacted (as I could tell):
- `Array.prototype.filter`
- `Array.prototype.map`
- `String.prototype.lastIndexOf`
All of these features are provided by polyfill.io, for IE7 & IE8

Solutions:
- Inline polyfill each of these (just like `contains`)
- try-catch approach, loading all features if `detectBrowserUnsupportedFeatures` couldn't even run

### loadScript

Proposed version that supports old IE:
```javascript
function loadScript(src, done) {
    var finished = false

    function handleLoad () {
      if (!finished) {
        finished = true
        done(src)
      }
    }
  
    function handleReadyStateChange () {
      if (!finished) {
        if (script.readyState === 'complete') {
          handleLoad()
        }
      }
    }
  
    function handleError () {
      if (!finished) {
        finished = true
        done(new Error('Failed to load script ' + src))
      }
    }
    var script = document.createElement('script')
    script.onload = handleLoad
    script.type = 'text/javascript'
    script.onreadystatechange = handleReadyStateChange
    script.onerror = handleError
    script.src = src
    document.head.appendChild(script)
}
```

**Comment by jquintozamora** [comment]
Hello @ridem , 
Thanks for pointing that out. 
PR's are welcome if you prefer. Otherwise, I'll update the code.
